// playground/svelte/src/components/box/BoxRegular.svelte
<script lang="ts">
  const text =
    'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Nam, repellendus modi quod quasi sunt voluptatem provident ex? Quis, officia provident sed ut iste quod delectus dolorem recusandae sit nihil? Perspiciatis temporibus ducimus minus reiciendis consectetur, id, vero, blanditiis mollitia ea deleniti aliquid. Vel harum odit corrupti beatae veniam quos ratione, sequi veritatis adipisci quis minima temporibus libero dolor quod perspiciatis at reiciendis nisi. Voluptas sunt repellat quidem omnis? Explicabo tempora totam, nisi enim veritatis ipsum reiciendis libero sit consequatur obcaecati dolorem nulla illum velit neque quisquam expedita quibusdam! Blanditiis cumque esse impedit dignissimos nesciunt quae commodi magnam accusamus qui repellendus!'

  let more = false
</script>

<div class="max-w-xl">
  <p class={more ? '' : 'line-clamp-3 '}>{text}</p>
  <button
    class="mt-4 flex w-full justify-center rounded-lg bg-light-bg-secondary p-3 font-semibold transition-colors hover:bg-light-bg-alternative dark:bg-dark-bg-secondary dark:hover:bg-dark-bg-alternative"
    on:click={() => (more = !more)}
  >
    {more ? 'less' : 'MORE'}
  </button>
</div>

// playground/vue/src/components/box/BoxRegular.vue
<script setup lang="ts">
import { ref } from 'vue'

const text =
  'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Nam, repellendus modi quod quasi sunt voluptatem provident ex? Quis, officia provident sed ut iste quod delectus dolorem recusandae sit nihil? Perspiciatis temporibus ducimus minus reiciendis consectetur, id, vero, blanditiis mollitia ea deleniti aliquid. Vel harum odit corrupti beatae veniam quos ratione, sequi veritatis adipisci quis minima temporibus libero dolor quod perspiciatis at reiciendis nisi. Voluptas sunt repellat quidem omnis? Explicabo tempora totam, nisi enim veritatis ipsum reiciendis libero sit consequatur obcaecati dolorem nulla illum velit neque quisquam expedita quibusdam! Blanditiis cumque esse impedit dignissimos nesciunt quae commodi magnam accusamus qui repellendus!'

const more = ref(false)
</script>

<template>
  <div class="max-w-xl">
    <p :class="{ 'line-clamp-3': !more }">{{ text }}</p>
    <button
      class="mt-4 flex w-full justify-center rounded-lg bg-light-bg-secondary p-3 font-semibold transition-colors hover:bg-light-bg-alternative dark:bg-dark-bg-secondary dark:hover:bg-dark-bg-alternative"
      @click="more = !more"
    >
      {{ more ? 'less' : 'MORE' }}
    </button>
  </div>
</template>
