// playground/svelte/src/App.svelte
<script lang="ts">
  import AccordionRegularOne from './components/accordion/AccordionRegularOne.svelte'
  import AccordionRegularTwo from './components/accordion/AccordionRegularTwo.svelte'
  import AccordionAnimated from './components/accordion/AccordionAnimated.svelte'
  import AccordionAnimatedRadio from './components/accordion/AccordionAnimatedRadio.svelte'
  import ShareRegular from './components/share/ShareRegular.svelte'
  import BoxRegular from './components/box/BoxRegular.svelte'
</script>

<div>
  <!-- <AccordionRegularOne /> -->
  <!-- <AccordionRegularTwo /> -->
  <!-- <AccordionAnimated /> -->
  <!-- <AccordionAnimatedRadio /> -->
  <!-- <ShareRegular /> -->
  <!-- <BoxRegular /> -->
</div>

// playground/solid/src/App.tsx
import AccordionRegularOne from './components/accordion/AccordionRegularOne'
import AccordionRegularTwo from './components/accordion/AccordionRegularTwo'
import AccordionAnimated from './components/accordion/AccordionAnimated'
import AccordionAnimatedRadio from './components/accordion/AccordionAnimatedRadio'
import ShareRegular from './components/share/ShareRegular'
import BoxRegular from './components/box/BoxRegular'

export default function App() {
  return (
    <div>
      {/* <AccordionRegularOne /> */}
      {/* <AccordionRegularTwo /> */}
      {/* <AccordionAnimated /> */}
      {/* <AccordionAnimatedRadio /> */}
      {/* <ShareRegular /> */}
      {/* <BoxRegular /> */}
    </div>
  )
}
