// playground/svelte/src/App.svelte
<script lang="ts">
  import AccordionRegularOne from './components/accordion/AccordionRegularOne.svelte'
  import AccordionRegularTwo from './components/accordion/AccordionRegularTwo.svelte'
  import AccordionAnimated from './components/accordion/AccordionAnimated.svelte'
  import AccordionAnimatedRadio from './components/accordion/AccordionAnimatedRadio.svelte'
</script>

<div>
  <!-- <AccordionRegularOne /> -->
  <!-- <AccordionRegularTwo /> -->
  <!-- <AccordionAnimated /> -->
  <!-- <AccordionAnimatedRadio /> -->
</div>

// playground/vue/src/App.vue
<script setup lang="ts">
import AccordionRegularOne from './components/accordion/AccordionRegularOne.vue'
import AccordionRegularTwo from './components/accordion/AccordionRegularTwo.vue'
import AccordionAnimated from './components/accordion/AccordionAnimated.vue'
import AccordionAnimatedRadio from './components/accordion/AccordionAnimatedRadio.vue'
</script>

<template>
  <div>
    <!-- <AccordionRegularOne /> -->
    <!-- <AccordionRegularTwo /> -->
    <!-- <AccordionAnimated /> -->
    <AccordionAnimatedRadio />
  </div>
</template>
